### ISSUE TITLE
Unable to import component: cannot import name 'enum24' from 'zigpy.types'

### ISSUE THREAD

**Issue by CloCkWeRX** [zigpy/zigpy-znp#269]
Regression? with https://github.com/zigpy/zigpy-znp/pull/268 vs https://github.com/zigpy/zigpy/pull/1747

With 
```
zha                           0.0.89
zha-quirks                    0.0.156
zigpy                         0.91.5
zigpy-deconz                  0.25.5
zigpy-xbee                    0.21.1
zigpy-zigate                  0.13.4
zigpy-znp                     0.14.3
```
I see:

```
Setup failed for 'zha': Unable to import component: cannot import name 'enum24' from 'zigpy.types' (/srv/homeassistant/lib/python3.13/site-packages/zigpy/types/__init__.py)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.13/site-packages/homeassistant/loader.py", line 1018, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.13/site-packages/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.13/site-packages/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/srv/homeassistant/lib/python3.13/site-packages/homeassistant/components/zha/__init__.py", line 8, in <module>
    from zha.application.const import BAUD_RATES, RadioType
  File "/srv/homeassistant/lib/python3.13/site-packages/zha/application/const.py", line 14, in <module>
    import zigpy_znp.zigbee.application
  File "/srv/homeassistant/lib/python3.13/site-packages/zigpy_znp/zigbee/application.py", line 27, in <module>
    import zigpy_znp.const as const
  File "/srv/homeassistant/lib/python3.13/site-packages/zigpy_znp/const.py", line 1, in <module>
    import zigpy_znp.types as t
  File "/srv/homeassistant/lib/python3.13/site-packages/zigpy_znp/types/__init__.py", line 3, in <module>
    from .basic import *  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.13/site-packages/zigpy_znp/types/basic.py", line 34, in <module>
    from zigpy.types import (  # noqa: F401
    ...<12 lines>...
    )
ImportError: cannot import name 'enum24' from 'zigpy.types' (/srv/homeassistant/lib/python3.13/site-packages/zigpy/types/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.13/site-packages/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.13/site-packages/homeassistant/loader.py", line 1038, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/srv/homeassistant/lib/python3.13/site-packages/homeassistant/loader.py", line 1030, in async_get_component
    comp = self._get_component()
  File "/srv/homeassistant/lib/python3.13/site-packages/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.13/site-packages/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/srv/homeassistant/lib/python3.13/site-packages/homeassistant/components/zha/__init__.py", line 8, in <module>
    from zha.application.const import BAUD_RATES, RadioType
  File "/srv/homeassistant/lib/python3.13/site-packages/zha/application/const.py", line 14, in <module>
    import zigpy_znp.zigbee.application
  File "/srv/homeassistant/lib/python3.13/site-packages/zigpy_znp/zigbee/application.py", line 27, in <module>
    import zigpy_znp.const as const
  File "/srv/homeassistant/lib/python3.13/site-packages/zigpy_znp/const.py", line 1, in <module>
    import zigpy_znp.types as t
  File "/srv/homeassistant/lib/python3.13/site-packages/zigpy_znp/types/__init__.py", line 3, in <module>
    from .basic import *  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.13/site-packages/zigpy_znp/types/basic.py", line 34, in <module>
    from zigpy.types import (  # noqa: F401
    ...<12 lines>...
    )
ImportError: cannot import name 'enum24' from 'zigpy.types' (/srv/homeassistant/lib/python3.13/site-packages/zigpy/types/__init__.py)
```

So potentially needs a minimum version constraint or similar?
But https://github.com/zigpy/zigpy/compare/0.90.0...0.91.0 should have the changes from upstream
Maybe should be zigpy.types.basic?

**Comment by puddly** [comment]
How are you running Home Assistant? This type of problem would have been caught instantly by CI, it sounds like there is something broken with your Python packages.

**Comment by CloCkWeRX** [comment]
Manual install, managed by pip and a venv.
Upgraded home assistant from 2025.12.something to 2026.2.1 via `pip install --upgrade homeassistant`


I would have thought it would be caught too. The existing coverage is only focused on `enum8`
https://github.com/zigpy/zigpy-znp/blob/dev/tests/test_types_basic.py
```
def test_enum_instance_types():
    class TestEnum(t.enum8):
        Member = 0x00

    assert TestEnum._member_type_ is t.uint8_t
    assert type(TestEnum.Member.value) is t.uint8_t
```

Since there's `TYPE_CHECKING` which decides whether to import or not; is there a chance the test cases are stubbing this in all cases?

**Comment by puddly** [comment]
It's not a problem with this package if the versions you posted above are indeed the ones you're using. I suspect your virtual environment may not be configured correctly, `uv` isn't installed, or something else.
